///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace First
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the FirstRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("76887d88-c8e2-49a6-bed0-bb446a6ea799")]
    public partial class FirstRepository : RepoGenBaseFolder
    {
        static FirstRepository instance = new FirstRepository();
        FirstRepositoryFolders.WelcomeMercuryToursAppFolder _welcomemercurytours;
        FirstRepositoryFolders.FindAFlightMercuryToursAppFolder _findaflightmercurytours;
        FirstRepositoryFolders.RegisterMercuryToursAppFolder _registermercurytours;

        /// <summary>
        /// Gets the singleton class instance representing the FirstRepository element repository.
        /// </summary>
        [RepositoryFolder("76887d88-c8e2-49a6-bed0-bb446a6ea799")]
        public static FirstRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public FirstRepository() 
            : base("FirstRepository", "/", null, 0, false, "76887d88-c8e2-49a6-bed0-bb446a6ea799", ".\\RepositoryImages\\FirstRepository76887d88.rximgres")
        {
            _welcomemercurytours = new FirstRepositoryFolders.WelcomeMercuryToursAppFolder(this);
            _findaflightmercurytours = new FirstRepositoryFolders.FindAFlightMercuryToursAppFolder(this);
            _registermercurytours = new FirstRepositoryFolders.RegisterMercuryToursAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("76887d88-c8e2-49a6-bed0-bb446a6ea799")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The WelcomeMercuryTours folder.
        /// </summary>
        [RepositoryFolder("9c8ffda8-a185-4878-8f3d-b6f9fb7915c2")]
        public virtual FirstRepositoryFolders.WelcomeMercuryToursAppFolder WelcomeMercuryTours
        {
            get { return _welcomemercurytours; }
        }

        /// <summary>
        /// The FindAFlightMercuryTours folder.
        /// </summary>
        [RepositoryFolder("d1151c92-927f-4ba6-b273-244319a3b087")]
        public virtual FirstRepositoryFolders.FindAFlightMercuryToursAppFolder FindAFlightMercuryTours
        {
            get { return _findaflightmercurytours; }
        }

        /// <summary>
        /// The RegisterMercuryTours folder.
        /// </summary>
        [RepositoryFolder("d75d1616-13dc-466a-a6a0-336c771ba8a8")]
        public virtual FirstRepositoryFolders.RegisterMercuryToursAppFolder RegisterMercuryTours
        {
            get { return _registermercurytours; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class FirstRepositoryFolders
    {
        /// <summary>
        /// The WelcomeMercuryToursAppFolder folder.
        /// </summary>
        [RepositoryFolder("9c8ffda8-a185-4878-8f3d-b6f9fb7915c2")]
        public partial class WelcomeMercuryToursAppFolder : RepoGenBaseFolder
        {
            FirstRepositoryFolders.SomeTableTagFolder _sometabletag;

            /// <summary>
            /// Creates a new WelcomeMercuryTours  folder.
            /// </summary>
            public WelcomeMercuryToursAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WelcomeMercuryTours", "/dom[@caption='Welcome: Mercury Tours' and @page='' and @path='/' and @browsername='Chrome']", parentFolder, 30000, null, false, "9c8ffda8-a185-4878-8f3d-b6f9fb7915c2", "")
            {
                _sometabletag = new FirstRepositoryFolders.SomeTableTagFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9c8ffda8-a185-4878-8f3d-b6f9fb7915c2")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9c8ffda8-a185-4878-8f3d-b6f9fb7915c2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeTableTag folder.
            /// </summary>
            [RepositoryFolder("4923b865-d7ba-4bc9-a25c-910fbcd00d8f")]
            public virtual FirstRepositoryFolders.SomeTableTagFolder SomeTableTag
            {
                get { return _sometabletag; }
            }
        }

        /// <summary>
        /// The SomeTableTagFolder folder.
        /// </summary>
        [RepositoryFolder("4923b865-d7ba-4bc9-a25c-910fbcd00d8f")]
        public partial class SomeTableTagFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _loginInfo;

            /// <summary>
            /// Creates a new SomeTableTag  folder.
            /// </summary>
            public SomeTableTagFolder(RepoGenBaseFolder parentFolder) :
                    base("SomeTableTag", "body/?/?/table/?/?/tr/td[2]/table/tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[2]/td[3]/form[@name='home']/table/tbody/tr[4]/?/?/table", parentFolder, 30000, null, false, "4923b865-d7ba-4bc9-a25c-910fbcd00d8f", "")
            {
                _usernameInfo = new RepoItemInfo(this, "UserName", "tbody/tr[2]/?/?/input[@name='userName']", 30000, null, "56b4c237-be24-47b4-ab04-2b88a5f87735");
                _passwordInfo = new RepoItemInfo(this, "Password", "tbody/tr[3]/?/?/input[@name='password']", 30000, null, "e4b6a602-5782-4cf2-a53e-09988e1c0d49");
                _loginInfo = new RepoItemInfo(this, "Login", ".//input[@name='login']", 30000, null, "c55ae3b9-9a35-42b8-a2dc-df39a8b93705");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4923b865-d7ba-4bc9-a25c-910fbcd00d8f")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4923b865-d7ba-4bc9-a25c-910fbcd00d8f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserName item.
            /// </summary>
            [RepositoryItem("56b4c237-be24-47b4-ab04-2b88a5f87735")]
            public virtual Ranorex.InputTag UserName
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserName item info.
            /// </summary>
            [RepositoryItemInfo("56b4c237-be24-47b4-ab04-2b88a5f87735")]
            public virtual RepoItemInfo UserNameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("e4b6a602-5782-4cf2-a53e-09988e1c0d49")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("e4b6a602-5782-4cf2-a53e-09988e1c0d49")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("c55ae3b9-9a35-42b8-a2dc-df39a8b93705")]
            public virtual Ranorex.InputTag Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("c55ae3b9-9a35-42b8-a2dc-df39a8b93705")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }
        }

        /// <summary>
        /// The FindAFlightMercuryToursAppFolder folder.
        /// </summary>
        [RepositoryFolder("d1151c92-927f-4ba6-b273-244319a3b087")]
        public partial class FindAFlightMercuryToursAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _profileInfo;

            /// <summary>
            /// Creates a new FindAFlightMercuryTours  folder.
            /// </summary>
            public FindAFlightMercuryToursAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FindAFlightMercuryTours", "/dom[@domain='newtours.demoaut.com']/body/?/?/table/?/?/tr/td[2]/table/tbody/tr[2]/?/?/table/?/?/tr/td[3]/a[@innertext='PROFILE']", parentFolder, 30000, null, false, "d1151c92-927f-4ba6-b273-244319a3b087", "")
            {
                _profileInfo = new RepoItemInfo(this, "Profile", "", 30000, null, "60520c60-9538-45da-bcc7-a55587a73a3f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d1151c92-927f-4ba6-b273-244319a3b087")]
            public virtual Ranorex.ATag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d1151c92-927f-4ba6-b273-244319a3b087")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Profile item.
            /// </summary>
            [RepositoryItem("60520c60-9538-45da-bcc7-a55587a73a3f")]
            public virtual Ranorex.ATag Profile
            {
                get
                {
                    return _profileInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Profile item info.
            /// </summary>
            [RepositoryItemInfo("60520c60-9538-45da-bcc7-a55587a73a3f")]
            public virtual RepoItemInfo ProfileInfo
            {
                get
                {
                    return _profileInfo;
                }
            }
        }

        /// <summary>
        /// The RegisterMercuryToursAppFolder folder.
        /// </summary>
        [RepositoryFolder("d75d1616-13dc-466a-a6a0-336c771ba8a8")]
        public partial class RegisterMercuryToursAppFolder : RepoGenBaseFolder
        {
            FirstRepositoryFolders.SomeTableTagFolder1 _sometabletag;
            RepoItemInfo _firstnameInfo;

            /// <summary>
            /// Creates a new RegisterMercuryTours  folder.
            /// </summary>
            public RegisterMercuryToursAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterMercuryTours", "/dom[@domain='newtours.demoaut.com']", parentFolder, 30000, null, false, "d75d1616-13dc-466a-a6a0-336c771ba8a8", "")
            {
                _sometabletag = new FirstRepositoryFolders.SomeTableTagFolder1(this);
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//input[@name='firstName']", 30000, null, "4e4674cb-23c8-4121-80e3-a0e50f58bf62");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d75d1616-13dc-466a-a6a0-336c771ba8a8")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d75d1616-13dc-466a-a6a0-336c771ba8a8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("4e4674cb-23c8-4121-80e3-a0e50f58bf62")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("4e4674cb-23c8-4121-80e3-a0e50f58bf62")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The SomeTableTag folder.
            /// </summary>
            [RepositoryFolder("00957152-fc39-427a-97f1-9a03b079b81f")]
            public virtual FirstRepositoryFolders.SomeTableTagFolder1 SomeTableTag
            {
                get { return _sometabletag; }
            }
        }

        /// <summary>
        /// The SomeTableTagFolder1 folder.
        /// </summary>
        [RepositoryFolder("00957152-fc39-427a-97f1-9a03b079b81f")]
        public partial class SomeTableTagFolder1 : RepoGenBaseFolder
        {
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _phoneInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _address1Info;
            RepoItemInfo _cityInfo;
            RepoItemInfo _stateInfo;
            RepoItemInfo _postalcodeInfo;
            RepoItemInfo _countryInfo;
            RepoItemInfo _httpnewtoursdemoautcomimagesprofiInfo;

            /// <summary>
            /// Creates a new SomeTableTag  folder.
            /// </summary>
            public SomeTableTagFolder1(RepoGenBaseFolder parentFolder) :
                    base("SomeTableTag", "body/?/?/table/?/?/tr/td[2]/table/tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/table", parentFolder, 30000, null, false, "00957152-fc39-427a-97f1-9a03b079b81f", "")
            {
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//input[@name='lastName']", 30000, null, "3cf528d9-17e9-4587-9f25-e59b3e086201");
                _phoneInfo = new RepoItemInfo(this, "Phone", "tbody/tr[4]/?/?/input[@name='phone']", 30000, null, "747d0119-b9aa-4cc7-aa75-67cd3c41b62b");
                _emailInfo = new RepoItemInfo(this, "Email", "tbody/tr[5]/?/?/input[@name='email']", 30000, null, "4536c635-465b-4069-b690-b1f96297c6be");
                _address1Info = new RepoItemInfo(this, "Address1", "tbody/tr[7]/?/?/input[@name='address1']", 30000, null, "bb5a18c1-512e-4302-b48b-1c433e166b66");
                _cityInfo = new RepoItemInfo(this, "City", "tbody/tr[9]/?/?/input[@name='city']", 30000, null, "1c744429-c1e5-4c5b-98a8-3feb8b4973bd");
                _stateInfo = new RepoItemInfo(this, "State", "tbody/tr[10]/?/?/input[@name='state']", 30000, null, "2d7b4dfd-2bd0-47f6-9eb2-bb819fceaf54");
                _postalcodeInfo = new RepoItemInfo(this, "PostalCode", "tbody/tr[11]/?/?/input[@name='postalCode']", 30000, null, "ad390e61-c06c-4840-9a4c-a65c59250561");
                _countryInfo = new RepoItemInfo(this, "Country", "tbody/tr[12]/?/?/select[@name='country']", 30000, null, "ffdc3078-df5e-4398-a32f-b475bdff408f");
                _httpnewtoursdemoautcomimagesprofiInfo = new RepoItemInfo(this, "HttpNewtoursDemoautComImagesProfi", "tbody/tr[14]/?/?/a[@href~'^http://newtours\\.demoaut\\.c']/img[@src='http://newtours.demoaut.com/images/profile_submit.gif']", 30000, null, "6e306e48-7be2-470f-84a2-b3057ed4897a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("00957152-fc39-427a-97f1-9a03b079b81f")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("00957152-fc39-427a-97f1-9a03b079b81f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("3cf528d9-17e9-4587-9f25-e59b3e086201")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("3cf528d9-17e9-4587-9f25-e59b3e086201")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Phone item.
            /// </summary>
            [RepositoryItem("747d0119-b9aa-4cc7-aa75-67cd3c41b62b")]
            public virtual Ranorex.InputTag Phone
            {
                get
                {
                    return _phoneInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Phone item info.
            /// </summary>
            [RepositoryItemInfo("747d0119-b9aa-4cc7-aa75-67cd3c41b62b")]
            public virtual RepoItemInfo PhoneInfo
            {
                get
                {
                    return _phoneInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("4536c635-465b-4069-b690-b1f96297c6be")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("4536c635-465b-4069-b690-b1f96297c6be")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The Address1 item.
            /// </summary>
            [RepositoryItem("bb5a18c1-512e-4302-b48b-1c433e166b66")]
            public virtual Ranorex.InputTag Address1
            {
                get
                {
                    return _address1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Address1 item info.
            /// </summary>
            [RepositoryItemInfo("bb5a18c1-512e-4302-b48b-1c433e166b66")]
            public virtual RepoItemInfo Address1Info
            {
                get
                {
                    return _address1Info;
                }
            }

            /// <summary>
            /// The City item.
            /// </summary>
            [RepositoryItem("1c744429-c1e5-4c5b-98a8-3feb8b4973bd")]
            public virtual Ranorex.InputTag City
            {
                get
                {
                    return _cityInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The City item info.
            /// </summary>
            [RepositoryItemInfo("1c744429-c1e5-4c5b-98a8-3feb8b4973bd")]
            public virtual RepoItemInfo CityInfo
            {
                get
                {
                    return _cityInfo;
                }
            }

            /// <summary>
            /// The State item.
            /// </summary>
            [RepositoryItem("2d7b4dfd-2bd0-47f6-9eb2-bb819fceaf54")]
            public virtual Ranorex.InputTag State
            {
                get
                {
                    return _stateInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The State item info.
            /// </summary>
            [RepositoryItemInfo("2d7b4dfd-2bd0-47f6-9eb2-bb819fceaf54")]
            public virtual RepoItemInfo StateInfo
            {
                get
                {
                    return _stateInfo;
                }
            }

            /// <summary>
            /// The PostalCode item.
            /// </summary>
            [RepositoryItem("ad390e61-c06c-4840-9a4c-a65c59250561")]
            public virtual Ranorex.InputTag PostalCode
            {
                get
                {
                    return _postalcodeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PostalCode item info.
            /// </summary>
            [RepositoryItemInfo("ad390e61-c06c-4840-9a4c-a65c59250561")]
            public virtual RepoItemInfo PostalCodeInfo
            {
                get
                {
                    return _postalcodeInfo;
                }
            }

            /// <summary>
            /// The Country item.
            /// </summary>
            [RepositoryItem("ffdc3078-df5e-4398-a32f-b475bdff408f")]
            public virtual Ranorex.SelectTag Country
            {
                get
                {
                    return _countryInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Country item info.
            /// </summary>
            [RepositoryItemInfo("ffdc3078-df5e-4398-a32f-b475bdff408f")]
            public virtual RepoItemInfo CountryInfo
            {
                get
                {
                    return _countryInfo;
                }
            }

            /// <summary>
            /// The HttpNewtoursDemoautComImagesProfi item.
            /// </summary>
            [RepositoryItem("6e306e48-7be2-470f-84a2-b3057ed4897a")]
            public virtual Ranorex.ImgTag HttpNewtoursDemoautComImagesProfi
            {
                get
                {
                    return _httpnewtoursdemoautcomimagesprofiInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpNewtoursDemoautComImagesProfi item info.
            /// </summary>
            [RepositoryItemInfo("6e306e48-7be2-470f-84a2-b3057ed4897a")]
            public virtual RepoItemInfo HttpNewtoursDemoautComImagesProfiInfo
            {
                get
                {
                    return _httpnewtoursdemoautcomimagesprofiInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}